### ISSUE TITLE
Bugs with Textures

### ISSUE THREAD

**Issue by ShrikerChestTrees** [BGP0/ResolutionControl-3#1]
I when I entered the world I was fine but after a while most of the textures disappeared.
Please find out what the problem is! 
![2024-07-07_12 06 42](https://github.com/BGP0/ResolutionControl-3/assets/163498687/57e45360-979a-4623-b7ff-51d730df0919)

**Comment by ShrikerChestTrees** [comment]
I fixed it by simply reloading the textures with F3+T.

**Comment by BGP0** [comment]
thats odd, please let me know if it happens again and join the discord maybe and say what other mods you were using and send log files.

Also @ShrikerChestTrees, I saw you were writing a lot in other repos before I released my update. How do you find my 1.21 fork? Does it all work correctly and meet your expectations? And is there anything else you think I should add?

**Comment by ShrikerChestTrees** [comment]
> Also @ShrikerChestTrees, I saw you were writing a lot in other repos before I released my update. How do you find my 1.21 fork? Does it all work correctly and meet your expectations? And is there anything else you think I should add?

To be honest I'm very surprised that you fixed the rendering bug in a while. 

You even took everything that was in the ResolutionControl++ mod and I was afraid that you would have problems with rendering but as I see that you got it all right! 

I am very proud that you had no problems with it (rendering)!


I noticed by the way that there is a blur with a GUI to change the rendering resolution. 
Try to make this GUI show clearly without blurring from minecraft.
