### ISSUE TITLE
ResolutionControl++ link bug (Modrinth, github)

### ISSUE THREAD

**Issue by ShrikerChestTrees** [BGP0/ResolutionControl-3#2]
When I click on the text "ResolutionControl++" it takes me not to github ResolutionControl++ but to github ResolutionControl+. 
Here's the github link to ResolutionControl++ if you need it: https://github.com/FlawCra/Resolution-Control
Fix this text-link please!
1. Resolution Control 3 (Modrinth)
2. Resolution Control+
3. Resolution Control++

1 ![Снимок экрана 2024-07-07 201827](https://github.com/BGP0/ResolutionControl-3/assets/163498687/f31e4beb-23dc-4b14-a743-8a48a361cbbd)

2 ![Снимок экрана 2024-07-07 201845](https://github.com/BGP0/ResolutionControl-3/assets/163498687/7bd006c5-164d-4247-8e56-ba280d7878fd)

3 ![Снимок экрана 2024-07-07 202128](https://github.com/BGP0/ResolutionControl-3/assets/163498687/a8f59351-9863-4845-97a1-2ebb2ec69745)

**Comment by BGP0** [comment]
make a pr if you want
